package:
  name: lsd
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}

source:
  git_url: ../

requirements:
  build:
    - python 2.7.*
    - numpy ==1.9
    - astropy
    - polygon
    - scipy
    - scikits-ann
    - requests
    - pytables
    - pyyaml
  run:
    - python 2.7.*
    - numpy >=1.9
    - astropy
    - polygon
    - scipy
    - scikits-ann
    - requests
    - pytables
    - pyyaml

test:
  # Python imports
  imports:
    - lsd
    - lsd.bounds
    - lsd.utils
    - lsd.tui
    - lsd.pool2

about:
  home: https://github.com/mjuric/lsd
